### ISSUE TITLE
Failed to add site

### ISSUE THREAD

**Issue by koi646** [0xJacky/nginx-ui#637]
**Describe the bug**
The front-end reports an error when add site

**To Reproduce**
1. start nginx-ui
2. complete config
![image](https://github.com/user-attachments/assets/b1fa76eb-51b8-4aed-bf01-e1f67d742583)
![image](https://github.com/user-attachments/assets/f00fbec9-7f30-4831-883e-7e23e9956c33)

**Expected behavior**
add site success

**Screenshots**

**Info (please complete the following information):**
 - Server OS: [aws linux2]
 - Server Arch: [x86]
 - Nginx UI Version: [2.0.0-beta.36]
 - Your Browser: [Arc]

**Additional context**
![image](https://github.com/user-attachments/assets/c5ea5802-c2b9-4c6c-8d11-4e58e5f867d5)

index-G7-zBUPw.js:14 TypeError: Cannot read properties of undefined (reading 'locations')
    at g (NgxConfigEditor-DZ7jt-DA.js:1:10698)
    at So (index-G7-zBUPw.js:14:1385)
    at Ot (index-G7-zBUPw.js:14:1456)
    at c0 (index-G7-zBUPw.js:15:32507)
    at h (index-ZHjQ4DE5.js:46:4037)
    at So (index-G7-zBUPw.js:14:1385)
    at Ot (index-G7-zBUPw.js:14:1456)
    at c0 (index-G7-zBUPw.js:15:32507)
    at J (index-Cv7sLCZk.js:1:18529)
    at So (index-G7-zBUPw.js:14:1385)

**Comment by koi646** [comment]
i think it just  ambiguous presentation at the front-end

**Comment by 0xJacky** [comment]
Please wait for the next beta version, thanks for your report.
